version: '3.1'

services:
  dbs:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'person'
    volumes:
      - 'person:/var/lib/postgresql/data'
      - './db:/usr/local/src/'
    ports:
      - '5433:5432'


volumes:
  person: